name: database_manager
description: Simple way to manage database. Version control and application's database schema. Simplify CRUD operations.
version: 0.0.1+2
author: Antonino Di Natale <gyorgio88@gmail.com>
homepage: https://github.com/Dn-a/database_manager

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
