name: database_manager
description: Simple way to manage database. Version control and application's database schema. Simplify CRUD operations.
version: 0.0.3+1
author: Antonino Di Natale <gyorgio88@gmail.com>
homepage: https://github.com/Dn-a/database_manager

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^1.3.0
  path: ^1.7
  path_provider: ^1.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
